### ISSUE TITLE
MSFS / FSUIPC 7 compatibility 

### ISSUE THREAD

**Issue by Flusinerd** [fsuipc-node/api#8]
Any chance this gets updated to work with MSFS and FSUIPC v7
Im building an cross sim acars, so I would greatly benefit from this.
If I can get some hints, I might be able to do it myself and create a PR.

Sincerely, Jan

**Comment by blackholegalaxy** [comment]
Hi @Flusinerd I'm currently reviewing the documentation for FSUIPC new gen. A lot of offsets have moved. I am still waiting for a more stable offset list from FSUIPC and was not able to find an up to date list of offset address and potential new entries. If we get some list, continuing this would be a breeze.

**Comment by Flusinerd** [comment]
Okay ty for the quick response. I managed to track down the issue to it not connecting due to the unknown simulator. I managed to "fix" it by calling the `globalInstance.open()` method without any parameters. This way it connects to any simulator also including fusipc v7. This works for me, since the offsets I use don't seem to have changed. 

This is my hacky fix:

https://github.com/Flusinerd/api/commit/0de1fdcc4d4b8532adf7a580f00b0b13512cd909

**Comment by blackholegalaxy** [comment]
Do you want to open a PR for this? It could do the trick while testing new offsets.

**Comment by Flusinerd** [comment]
Sure :)

**Comment by Flusinerd** [comment]
Done
https://github.com/fsuipc-node/api/pull/9

**Comment by Flusinerd** [comment]
@blackholegalaxy 
https://github.com/koesie10/fsuipc-node/pull/8
I created a pull request for the ``fsuipc`` node module. This adds MSFS to the Simulators enum.
Once this gets merged, we can go back to the default behavior.

**Comment by blackholegalaxy** [comment]
If original `fsuipc` node module owner doesn't merge, we could fork the core module on our scope and create a `@fsuipc/core` package. You would just have to point your pull request to https://github.com/fsuipc-node/core
